services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pierre-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    volumes:
      - pierre-rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
  rustfs:
    image: rustfs/rustfs:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      RUSTFS_ACCESS_KEY: admin
      RUSTFS_SECRET_KEY: password
      RUSTFS_NOTIFY_ENABLE: true
      RUSTFS_NOTIFY_WEBHOOK_ENABLE_PRIMARY: on
      RUSTFS_NOTIFY_WEBHOOK_ENDPOINT_PRIMARY: https://winnerx0.outray.app/upload-webhook
      RUSTFS_NOTIFY_WEBHOOK_QUEUE_DIR_PRIMARY: /data/output
      RUSTFS_OUTBOUND_ALLOW_ORIGINS: https://winnerx0.outray.app
    volumes:
      - pierre-rustfs:/data
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./backend:/app
  #   depends_on:
  #     - db
  #     - rabbitmq
  #     - rustfs
volumes:
  minio-data:
  pierre-data:
  pierre-rabbitmq:
  pierre-rustfs:
